name: CI-CD Pipeline

# ⬇️ IMPORTANT: GHCR push ke liye yeh block must hai
permissions:
  contents: read
  packages: write

on:
  push:
    branches: ["main"]
  pull_request:

env:
  IMAGE_NAME: demoapp
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java for Sonar Scanner
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push Docker Image
        run: docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Image
        run: docker pull $REGISTRY/$IMAGE_NAME:latest

      - name: Run Container
        run: |
          docker run -d -p 8080:8080 --name ci-cd-app $REGISTRY/$IMAGE_NAME:latest
